import '@/assets/globals.scss'
import { TokenProvider } from '@/context/tokenContext'
import SessionWrapper from '@/wrapper/sessionWrapper'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Test App',
    description: 'Generated by Nahid',
}

interface Props {
    children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Props>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <AntdRegistry>
                    <SessionWrapper>
                        <TokenProvider>{children}</TokenProvider>
                    </SessionWrapper>
                </AntdRegistry>
            </body>
        </html>
    )
}
